print("Welcome to the Mello Band")
city = input("Which city did you grow up in?\n")
pet = input("What is the name of a pet?\n")
print("your band name could be" + city + " " + pet)
print("Alright" + input("what is your major?\n"))
name = input("what is your name?\n")
Length = len(name)
print(Length)
old = input("How old are you?\n")
Height = input("how tall are you?\n")
print(old)
print(Height)
